name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "backlog"]
projects: ["jbfredheim/4"]
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: Tell us what happened. Please be as descriptive as possible.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: How can we reproduce it?
      description: Tell us, in as much detail as possible, how we can reproduce this bug.
      placeholder: What did you do to make this happen?
      value: "I did this, then this, then this, and then it happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Tell us what you expected to happen.
      placeholder: What did you expect to happen?
      value: "I expected this to happen!"
    validations:
        required: true
  - type: dropdown
    id: device-type
    attributes:
      label: What device type are you using?
      description: Tell us what device type you are using.
      options:
        - "PC/Mac"
        - "Phone"
        - "Tablet"
      default: 0
    validations:
        required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      description: Tell us what browser you are using.
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Other"
      default: 0
    validations:
        required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Tell us anything else you think we should know.
      placeholder: Anything else we should know?
      value: "Nothing else!"
    validations:
      required: false

